config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  #
  root "sessions#new"

  resources :pictures, only: [ :index, :new, :create ] do
    member do
      post :tweet
    end
  end

  resources :sessions, only: [ :new, :create, :destroy ]
  resources :oauth, only: [ :new ] do
    collection do
      get :callback
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :user

  has_one_attached :image

  validates :title, presence: true, length: { maximum: 30 }
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :pictures

  validates :login_id,        presence: true, uniqueness: { case_sensitive: false }
  validates :password_digest, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  private

  def authenticate_user!
    unless authenticated?
      redirect_to root_path
    end
  end
end

app/controllers/oauth_controller.rb
require "net/http"
require "uri"

class OauthController < ApplicationController
  def new
    base_url = ENV["OAUTH_BASE_URL"] + "authorize?"
    query_params = {
      client_id: ENV["CLIENT_ID"],
      response_type: "code",
      redirect_uri: "http://localhost:3000/oauth/callback",
      scope: "write_tweet"
    }
    query_string = query_params.map do |key, value|
      "#{key}=#{value}"
    end.join("&")

    redirect_to base_url + query_string, allow_other_host: true
  end

  def callback
    code = params["code"]

    if code
      url = ENV["OAUTH_BASE_URL"] + "token"

      params = {
        code:,
        client_id: ENV["CLIENT_ID"],
        client_secret: ENV["CLIENT_SECRET"],
        redirect_uri: "http://localhost:3000/oauth/callback",
        grant_type: "authorization_code"
      }

      response = HttpRequestBase.new().post_request(url, params)
      body = JSON.parse(response.body)

      if body["access_token"]
        session[:access_token] = body["access_token"]
        redirect_to pictures_path
      end
    else
      head :no_content
    end
  end

  private

  def generate_query_string(query_params)
    query_params.map do |key, value|
      "#{key}=#{value}"
    end.join("&")
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  include ActiveStorage::SetCurrent

  before_action :authenticate_user!
  before_action :set_picture, only: [ :tweet ]

  def index
    @pictures = current_user.pictures.order(id: :desc)
  end

  def create
    @errors = []

    @picture = current_user.pictures.build(picture_params)

    title = picture_params["title"]
    if title.blank?
      @errors.push("タイトルを入力してください。")
    end

    image = picture_params["image"]
    if image.blank?
      @errors.push ("画像ファイルを選択してください。")
    end

    unless @errors.blank?
      create_error()
      return
    end

    begin
      ActiveRecord::Base.transaction do
        @picture.save!
      end

      redirect_to pictures_path
    rescue ActiveRecord::RecordInvalid => e
      create_error(e.record.errors.full_messages)
      nil
    end
  end

  def tweet
    headers = {
      "Content-Type" => "application/json",
      "Authorization" => "Bearer #{session[:access_token]}"
    }

    params = {
      text: @picture.title,
      url: @picture.image.url
    }
    response = HttpRequestBase.new().post_request(ENV["TWEET_BASE_URL"], params, headers)

    redirect_to pictures_path
  end

  private

  def set_picture
    @picture = current_user.pictures.find(params[:id])
  rescue ActiveRecord::RecordNotFound => e
    redirect_to pictures_path
  end

  def picture_params
    params.require(:picture).permit(:title, :image)
  end

  def create_error(message = nil)
    @errors.push(message) if message
    @errors.flatten!
    render action: :new
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @errors = []

    login_id = session_params["login_id"]
    if login_id.blank?
      @errors.push("ユーザーIDを入力してください。")
    end

    password = session_params["password"]
    if password.blank?
      @errors.push("パスワードを入力してください。")
    end

    unless @errors.blank?
      login_error()
      return
    end

    user = User.find_by(login_id:)&.authenticate(password)

    if user
      login(user)
      redirect_to pictures_path
    else
      login_error("ユーザーIDまたはパスワードが間違っています。確認してください。")
    end
  end

  def destroy
    logout(@current_user)
    redirect_to root_path
  end

  private

  def session_params
    params.require(:session).permit(:login_id, :password)
  end

  def login_error(message = nil)
    @errors.push(message) if message
    render action: :new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def login(user)
    session[:login_id] = user.login_id
    current_user
  end

  def logout(user)
    session.delete :login_id
    session.delete :access_token
    @current_user = nil
  end

  def current_user
    @current_user ||= User.find_by(login_id: session[:login_id])
  end

  def authenticated?
    current_user.present?
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "App" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pictures/index.html.erb
<%= render partial: 'shared/logout' %>

<h1>写真一覧</h1>

<div><%= link_to "写真アップロード画面へ", new_picture_path %></div>

<div>
  <%= link_to "MyTweetAppと連携する", new_oauth_path  %></div>

<div class="pictures">
  <% @pictures.each do |picture| %>
  <div>
    <p><%= picture.title %></p>

    <div class="image_box">
      <%= image_tag picture.image, class: 'thumbnail' %>
    </div>

    <div>
      <%= button_to 'tweet', tweet_picture_path(picture) %>
    </div>
  </div>
  <% end %>
</div>

app/views/pictures/new.html.erb
<%= render partial: 'shared/logout' %>

<h1>写真アップロード</h1>

<%= render partial: 'shared/errors' %>

<%= form_for :picture, model: @picture, url: '/pictures/', method: :post do |form| %>
<div>
  <%= form.label :title, "タイトル" %>
  <%= form.search_field :title %>
</div>

<div>
  <%= form.label :image, "画像ファイル" %>
  <%= form.file_field :image, accept: 'image/*' %>
</div>

<div>
  <%= form.submit "アップロードする" %>
</div>
<% end %>

<br>

<div>
  <%= link_to "キャンセルする", pictures_path %>
</div>

app/views/shared/_errors.html.erb
<% if @errors.present? %>
  <ul>
  <% @errors.each do |message| %>
    <li class="error"><%= message %></li>
  <% end %>
  </ul>
<% end %>

app/views/shared/_logout.html.erb
<%= button_to "ログアウト", session_path(@current_user), method: :delete %>